name: Deploy sinch-ds to production
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and Push Docker Image
        run: |
          docker build -t digitalsamba376/sinch-ds:${{ github.ref_name }} -f Dockerfile-prod .
          docker push digitalsamba376/sinch-ds:${{ github.ref_name }}
      
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo docker pull digitalsamba376/sinch-ds:${{ github.ref_name }}
            sudo docker stop sinch-ds-prod || true
            sudo docker rm sinch-ds-prod || true
            sudo docker run -d --rm \
                            --name sinch-ds-prod \
                            --network deployment_proxy \
                            -p 4040:3030 \
                            -e VIRTUAL_HOST=${{ secrets.PRODUCTION_HOST }} \
                            -e LETSENCRYPT_HOST=${{ secrets.PRODUCTION_HOST }} \
                            -e VIRTUAL_PORT=3030 \
                            digitalsamba376/sinch-ds:${{ github.ref_name }}
